### PR TITLE
T6718: use the vyconf daemon for validation of set commands

### PR DESCRIPTION
**Pull request by jestabro**
## Change Summary

This PR has been updated with appropriate commit hashes in build.sh, following merge of
https://github.com/vyos/vyos1x-config/pull/31
https://github.com/vyos/vyconf/pull/11
and is ready for review.

It is required by the corresponding PR for vyos-1x.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Related PR(s)

https://github.com/vyos/vyos1x-config/pull/31
https://github.com/vyos/vyconf/pull/11

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]
This will certainly work, but I wonder if we should package vyconf and its tools separately at a later point.

**Comment by jestabro** [comment]
Now that we have the whole of vyconf available, I expect we will want to refactor the distinction vyconf <-> vyos1x-config as well as packaging.

**Review by sarthurdev — APPROVED** [review]

**Review by sever-sever — APPROVED** [review]

**Comment by jestabro** [comment]
This will benefit from a single commit PR for vyos-1x before merging, to make for a smooth transition (as ctypes do not, as far as I know, have a notion of optional argument, we must introduce a keyword argument  with default for the python wrapper `reference_tree_to_json`, to accommodate the change in the underlying function). The remainder of the vyos-1x PR https://github.com/vyos/vyos-1x/pull/4176 will be opened after updates to the Dockerfile, etc.

**Comment by jestabro** [comment]
After this merge, the update to the Docker file to reflect new commit hash will need to be accompanied by:
https://github.com/vyos/vyos-1x/pull/4226
to avoid a chicken-and-egg problem with build time generation of the reference tree.

**Pull request merged**
